/* (ASYNC) */
export const FETCH_ACCOUNT_DRIVER_INIT = 'FETCH_ACCOUNT_DRIVER_INIT';
export const FETCH_ACCOUNT_DRIVER_SUCCESS = 'FETCH_ACCOUNT_DRIVER_SUCCESS';
export const FETCH_ACCOUNT_DRIVER_FAILURE = 'FETCH_ACCOUNT_DRIVER_FAILURE';
