/* (ASYNC) */
export const FETCH_ACCOUNT_VEHICLE_INIT = 'FETCH_ACCOUNT_VEHICLE_INIT';
export const FETCH_ACCOUNT_VEHICLE_SUCCESS = 'FETCH_ACCOUNT_VEHICLE_SUCCESS';
export const FETCH_ACCOUNT_VEHICLE_FAILURE = 'FETCH_ACCOUNT_VEHICLE_FAILURE';

export const FETCH_ACCOUNT_VEHICLE_COUNT_INIT = 'FETCH_ACCOUNT_VEHICLE_COUNT_INIT';
export const FETCH_ACCOUNT_VEHICLE_COUNT_SUCCESS = 'FETCH_ACCOUNT_VEHICLE_COUNT_SUCCESS';
export const FETCH_ACCOUNT_VEHICLE_COUNT_FAILURE = 'FETCH_ACCOUNT_VEHICLE_COUNT_FAILURE';

export const FETCH_ACCOUNT_VEHICLE_NO_LOADING_INIT = 'FETCH_ACCOUNT_VEHICLE_NO_LOADING_INIT';
export const FETCH_ACCOUNT_VEHICLE_NO_LOADING_SUCCESS = 'FETCH_ACCOUNT_VEHICLE_NO_LOADING_SUCCESS';
export const FETCH_ACCOUNT_VEHICLE_NO_LOADING_FAILURE = 'FETCH_ACCOUNT_VEHICLE_NO_LOADING_FAILURE';

export const SAVE_ACCOUNT_VEHICLE_INIT = 'SAVE_ACCOUNT_VEHICLE_INIT';
export const SAVE_ACCOUNT_VEHICLE_SUCCESS = 'SAVE_ACCOUNT_VEHICLE_SUCCESS';
export const SAVE_ACCOUNT_VEHICLE_FAILURE = 'SAVE_ACCOUNT_VEHICLE_FAILURE';