/* (SYNC) */


/* (ASYNC) */
export const FETCH_DETAIL_FATIGUE_INIT = 'FETCH_DETAIL_FATIGUE_INIT';
export const FETCH_DETAIL_FATIGUE_SUCCESS = 'FETCH_DETAIL_FATIGUE_SUCCESS';
export const FETCH_DETAIL_FATIGUE_FAILURE = 'FETCH_DETAIL_FATIGUE_FAILURE';
