export const FETCH_SUMMARY_FULFILLMENT_INIT = 'FETCH_SUMMARY_FULFILLMENT_INIT';
export const FETCH_SUMMARY_FULFILLMENT_SUCCESS = 'FETCH_SUMMARY_FULFILLMENT_SUCCESS';
export const FETCH_SUMMARY_FULFILLMENT_FAILURE = 'FETCH_SUMMARY_FULFILLMENT_FAILURE';
