export const RESET_LOGIN = 'RESET_LOGIN';
export const LOG_OUT = 'LOG_OUT';

/* (ASYNC) */
export const SAVE_LOGIN_INIT = 'SAVE_LOGIN_INIT';
export const SAVE_LOGIN_SUCCESS = 'SAVE_LOGIN_SUCCESS';
export const SAVE_LOGIN_FAILURE = 'SAVE_LOGIN_FAILURE';