/* (SYNC) */
export const RESET_TAGS = 'RESET_TAGS';

/* (ASYNC) */
export const FETCH_TAGS_INIT = 'FETCH_TAGS_INIT';
export const FETCH_TAGS_SUCCESS = 'FETCH_TAGS_SUCCESS';
export const FETCH_TAGS_FAILURE = 'FETCH_TAGS_FAILURE';

export const FETCH_TAG_FATIGUE_INIT = 'FETCH_TAG_FATIGUE_INIT';
export const FETCH_TAG_FATIGUE_SUCCESS = 'FETCH_TAG_FATIGUE_SUCCESS';
export const FETCH_TAG_FATIGUE_FAILURE = 'FETCH_TAG_FATIGUE_FAILURE';
