/* (SYNC) */


/* (ASYNC) */
export const FETCH_SUMMARY_FATIGUE_INIT = 'FETCH_SUMMARY_FATIGUE_INIT';
export const FETCH_SUMMARY_FATIGUE_SUCCESS = 'FETCH_SUMMARY_FATIGUE_SUCCESS';
export const FETCH_SUMMARY_FATIGUE_FAILURE = 'FETCH_SUMMARY_FATIGUE_FAILURE';
