/* (ASYNC) */
export const FETCH_DASHBOARD_INIT = 'FETCH_DASHBOARD_INIT';
export const FETCH_DASHBOARD_SUCCESS = 'FETCH_DASHBOARD_SUCCESS';
export const FETCH_DASHBOARD_FAILURE = 'FETCH_DASHBOARD_FAILURE';

export const FETCH_DASHBOARD_DATE_INIT = 'FETCH_DASHBOARD_DATE_INIT';
export const FETCH_DASHBOARD_DATE_SUCCESS = 'FETCH_DASHBOARD_DATE_SUCCESS';
export const FETCH_DASHBOARD_DATE_FAILURE = ' FETCH_DASHBOARD_DATE_FAILURE';

export const RESET_DASHBOARD = 'RESET_DASHBOARD';