export const FETCH_DETAIL_BEHAVIOUR_INIT = 'FETCH_DETAIL_BEHAVIOUR_INIT';
export const FETCH_DETAIL_BEHAVIOUR_SUCCESS = 'FETCH_DETAIL_BEHAVIOUR_SUCCESS';
export const FETCH_DETAIL_BEHAVIOUR_FAILURE = 'FETCH_DETAIL_BEHAVIOUR_FAILURE';
