/* (ASYNC) */
export const FETCH_HOMOLOGATION_DRIVER_INIT = 'FETCH_HOMOLOGATION_DRIVER_INIT';
export const FETCH_HOMOLOGATION_DRIVER_SUCCESS = 'FETCH_HOMOLOGATION_DRIVER_SUCCESS';
export const FETCH_HOMOLOGATION_DRIVER_FAILURE = 'FETCH_HOMOLOGATION_DRIVER_FAILURE';
export const SAVE_HOMOLOGATION_DRIVER_INIT = 'SAVE_HOMOLOGATION_DRIVER_INIT';
export const SAVE_HOMOLOGATION_DRIVER_SUCCESS = 'SAVE_HOMOLOGATION_DRIVER_SUCCESS';
export const SAVE_HOMOLOGATION_DRIVER_FAILURE = 'SAVE_HOMOLOGATION_DRIVER_FAILURE';
