/* (ASYNC) */
export const FETCH_HOMOLOGATION_VEHICLE_INIT = 'FETCH_HOMOLOGATION_VEHICLE_INIT';
export const FETCH_HOMOLOGATION_VEHICLE_SUCCESS = 'FETCH_HOMOLOGATION_VEHICLE_SUCCESS';
export const FETCH_HOMOLOGATION_VEHICLE_FAILURE = 'FETCH_HOMOLOGATION_VEHICLE_FAILURE';
export const SAVE_HOMOLOGATION_VEHICLE_INIT = 'SAVE_HOMOLOGATION_VEHICLE_INIT';
export const SAVE_HOMOLOGATION_VEHICLE_SUCCESS = 'SAVE_HOMOLOGATION_VEHICLE_SUCCESS';
export const SAVE_HOMOLOGATION_VEHICLE_FAILURE = 'SAVE_HOMOLOGATION_VEHICLE_FAILURE';
