export const FETCH_DRIVER_FULFILLMENT_INIT = 'FETCH_DRIVER_FULFILLMENT_INIT';
export const FETCH_DRIVER_FULFILLMENT_SUCCESS = 'FETCH_DRIVER_FULFILLMENT_SUCCESS';
export const FETCH_DRIVER_FULFILLMENT_FAILURE = 'FETCH_DRIVER_FULFILLMENT_FAILURE';
