/* (ASYNC) */
export const FETCH_SUMMARY_BEHAVIOUR_INIT = 'FETCH_SUMMARY_BEHAVIOUR_INIT';
export const FETCH_SUMMARY_BEHAVIOUR_SUCCESS = 'FETCH_SUMMARY_BEHAVIOUR_SUCCESS';
export const FETCH_SUMMARY_BEHAVIOUR_FAILURE = 'FETCH_SUMMARY_BEHAVIOUR_FAILURE';
