/* (ASYNC) */
export const FETCH_SUMMARY_ROADWARNING_INIT = 'FETCH_SUMMARY_ROADWARNING_INIT';
export const FETCH_SUMMARY_ROADWARNING_SUCCESS = 'FETCH_SUMMARY_ROADWARNING_SUCCESS';
export const FETCH_SUMMARY_ROADWARNING_FAILURE = 'FETCH_SUMMARY_ROADWARNING_FAILURE';