export const FETCH_SUMMARY_SUMMARY_INIT = 'FETCH_SUMMARY_SUMMARY_INIT';
export const FETCH_SUMMARY_SUMMARY_SUCCESS = 'FETCH_SUMMARY_SUMMARY_SUCCESS';
export const FETCH_SUMMARY_SUMMARY_FAILURE = 'FETCH_SUMMARY_SUMMARY_FAILURE';
