export const FETCH_DETAIL_FULFILLMENT_INIT = 'FETCH_DETAIL_FULFILLMENT_INIT';
export const FETCH_DETAIL_FULFILLMENT_SUCCESS = 'FETCH_DETAIL_FULFILLMENT_SUCCESS';
export const FETCH_DETAIL_FULFILLMENT_FAILURE = 'FETCH_DETAIL_FULFILLMENT_FAILURE';
