export const FETCH_DETAIL_ROADWARNING_INIT = 'FETCH_DETAIL_ROADWARNING_INIT';
export const FETCH_DETAIL_ROADWARNING_SUCCESS = 'FETCH_DETAIL_ROADWARNING_SUCCESS';
export const FETCH_DETAIL_ROADWARNING_FAILURE = 'FETCH_DETAIL_ROADWARNING_FAILURE';
